config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  devise_for :users

  resources :entlies, only: [:new, :create, :update, :edit, :destroy]

  resources :users do
    resources :entlies, only: [:show]
  end

end

app/models/ently.rb
class Ently < ActiveRecord::Base
  validates :content, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true, length: { maximum: 30 }

  has_many :entlies, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    # sign_upのときに、usernameも許可する
    devise_parameter_sanitizer.for(:sign_up) << :name
    #  account_updateのときに、usernameも許可する
    devise_parameter_sanitizer.for(:account_update) << :name
  end

end

app/controllers/entlies_controller.rb
class EntliesController < ApplicationController
  before_action :set_ently, only: [:show, :edit, :update, :destroy]

  def show
    @user = User.find(params[:user_id])
  end


  def new
    @ently = current_user.entlies.build
  end

  def edit
  end

  def create
    @ently = current_user.entlies.build(entry_params)

    respond_to do |format|
      if @ently.save
        format.html { redirect_to user_ently_path(current_user.id, @ently.id), notice: 'Ently was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @ently.update(entry_params)
        format.html { redirect_to user_ently_path(current_user.id, @ently.id), notice: 'Ently was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end


  def destroy
    @ently.destroy
    respond_to do |format|
      format.html { redirect_to current_user.entlies.present? ? user_path(current_user) : "/", notice: 'Ently was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ently
      @ently = Ently.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:ently).permit(:content)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @ently = @user.entlies.last
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entlies/_form.html.haml
%b 週報投稿

= form_for (@ently) do |f|
  = render 'shared/error_messages', object: f.object
  .field
    = f.text_area :content, placeholder: "Compose new post..."
  = f.submit "Post", class: "btn btn-large btn-primary"

app/views/entlies/_show.html.haml
.row
  .col-md-8
    %p#notice= notice
    %p
      %b Content
      %br
        = simple_format(h(@ently.content))
        %br
        -if @ently.user == current_user
          = link_to 'Edit', edit_ently_path(@ently)
          \|
          = link_to 'destroy', ently_path(@ently), method: :delete, data: { :confirm => 'Are you sure?' }

  .col-md-4
    = render 'entlies/user_entlies'

app/views/entlies/_user_entlies.html.haml
%h1 entlies

%table
  %thead
    %tr
      %th
      %th
  %tbody
    - @user.entlies.each do |ently|
      %tr
        %td= "■"
        %td= link_to truncate(ently.content.lines.first, lingth: 10), user_ently_path(ently.user, ently)

app/views/entlies/new.html.haml
= render 'form'

app/views/entlies/show.html.haml
= render 'show'

app/views/home/index.html.haml
HOME

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
- if user_signed_in?
  %li= link_to 'Edit account', edit_user_registration_path
  %li= link_to 'Sign out', destroy_user_session_path, :method=>'delete'
  %li= link_to '週報をかく', edit_user_registration_path
- else
  %li= link_to 'Sign in', new_user_session_path
  %li= link_to 'Sign up', new_user_registration_path
.

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Academy0605'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Academy0605'}"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      .row
        .col-md-3
          = render "users/users"
        .col-md-9
          = yield

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Academy0602
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav
      - if user_signed_in?
        Logged in as
        = succeed "." do
          %strong= current_user.email
        = link_to 'プロフィール変更', edit_user_registration_path
        = link_to "ログアウト", destroy_user_session_path, method: :delete
        = link_to '週報を書く', new_post_path
        = link_to 'HOME', '/'
      - else
        = link_to 'サインイン', new_user_registration_path
        = link_to 'ログイン', new_user_session_path
    = yield

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-error
      The form contains #{pluralize(object.errors.count, "error")}.
    %ul
      - object.errors.full_messages.each do |msg|
        %li
          * #{msg}

app/views/users/_user.html.haml
-if user.entlies.present?
  %td= "（写）"
  %td= link_to user.name, user

app/views/users/_users.html.haml
.container
  .row
    %h3 Users
    .column
      %table
        %tbody
          - User.all.each do |user|
            %tr
              = render user

app/views/users/show.html.haml
= render 'entlies/show'